"""comment unique 

Revision ID: 02c70f7574d4
Revises: 36cac0a99c68
Create Date: 2025-12-12 08:15:03.845583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02c70f7574d4'
down_revision: Union[str, Sequence[str], None] = '36cac0a99c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_comments', 'slug',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('slug'), table_name='blog_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('slug'), 'blog_comments', ['slug'], unique=True)
    op.alter_column('blog_comments', 'slug',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
