"""Add quantity to artworks

Revision ID: 0e5425a8aae6
Revises: 24aa8700d39a
Create Date: 2025-08-13 08:20:31.003077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e5425a8aae6'
down_revision: Union[str, Sequence[str], None] = '24aa8700d39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'quantity')
    # ### end Alembic commands ###
