"""adding isActive and isDeleted flag 2

Revision ID: 1d9281661e0f
Revises: 8e1716ff182c
Create Date: 2025-09-03 10:34:01.716044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d9281661e0f'
down_revision: Union[str, Sequence[str], None] = '8e1716ff182c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isActive')
    op.drop_column('artworks', 'isDeleted')
    # ### end Alembic commands ###
