"""moved artwork images to ArtworkImage table

Revision ID: 20f075ba4f91
Revises: 6ad9912154a9
Create Date: 2025-09-01 09:14:59.584128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20f075ba4f91'
down_revision: Union[str, Sequence[str], None] = '6ad9912154a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('images', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
