"""new for agent

Revision ID: 21b0214fa246
Revises: 21613bb6f364
Create Date: 2025-11-30 08:46:41.600956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21b0214fa246'
down_revision: Union[str, Sequence[str], None] = '21613bb6f364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_reviews', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('artworks', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('comments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('reviews', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'status')
    op.drop_column('comments', 'status')
    op.drop_column('artworks', 'status')
    op.drop_column('artist_reviews', 'status')
    # ### end Alembic commands ###
