"""added relationship in artwork to community artwork

Revision ID: 289c912dea66
Revises: e1c664ef60c8
Create Date: 2025-12-08 09:01:26.084516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '289c912dea66'
down_revision: Union[str, Sequence[str], None] = 'e1c664ef60c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_artworks', sa.Column('artwork_id', sa.String(length=36), nullable=False))
    op.alter_column('community_artworks', 'community_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('community_artworks', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'community_artworks', 'artworks', ['artwork_id'], ['id'])
    op.drop_column('community_artworks', 'content')
    op.drop_column('community_artworks', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_artworks', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('community_artworks', sa.Column('content', mysql.TEXT(), nullable=False))
    op.drop_constraint(None, 'community_artworks', type_='foreignkey')
    op.alter_column('community_artworks', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('community_artworks', 'community_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_column('community_artworks', 'artwork_id')
    # ### end Alembic commands ###
