"""adding pincode and phone 

Revision ID: 31b530cf9b28
Revises: 01291040681d
Create Date: 2025-06-30 07:25:24.137030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31b530cf9b28'
down_revision: Union[str, Sequence[str], None] = '01291040681d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pincode', sa.CHAR(length=6), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'pincode')
    # ### end Alembic commands ###
