"""adding artworkimage table

Revision ID: 335908776d30
Revises: 9f7ecde091d5
Create Date: 2025-09-01 07:36:41.808457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '335908776d30'
down_revision: Union[str, Sequence[str], None] = '9f7ecde091d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artwork_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(500), nullable=False),
    sa.Column('public_id', sa.String(255), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork_images')
    # ### end Alembic commands ###
