"""content id to uuid

Revision ID: 38b81979fccb
Revises: 5f45941243e9
Create Date: 2025-12-01 07:41:30.439485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38b81979fccb'
down_revision: Union[str, Sequence[str], None] = '5f45941243e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation_queue', 'content_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moderation_queue', 'content_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
