"""add purchase_quantity to cart

Revision ID: 3d8cdf4ee52b
Revises: 0e5425a8aae6
Create Date: 2025-08-14 07:34:01.960654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d8cdf4ee52b'
down_revision: Union[str, Sequence[str], None] = '0e5425a8aae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artworks', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('cart', sa.Column('purchase_quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'purchase_quantity')
    op.alter_column('artworks', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
