"""changed wishlist to saved

Revision ID: 41eb479e28b1
Revises: d53d0190b071
Create Date: 2025-09-22 07:52:59.872033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41eb479e28b1'
down_revision: Union[str, Sequence[str], None] = 'd53d0190b071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('artworkId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['artworkId'], ['artworks.id'], name=op.f('wishlist_ibfk_1')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('wishlist_ibfk_2')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
