"""solved circular dependency issue

Revision ID: 695c8e961386
Revises: e4acb1b4a2b5
Create Date: 2025-12-08 09:53:13.122766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '695c8e961386'
down_revision: Union[str, Sequence[str], None] = 'e4acb1b4a2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_members', 'community_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('community_members', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_members', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('community_members', 'community_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
