"""added TandC and for sale in models

Revision ID: 6a85f5c7804d
Revises: 1d9281661e0f
Create Date: 2025-09-17 08:39:24.485598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a85f5c7804d'
down_revision: Union[str, Sequence[str], None] = '1d9281661e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('forSale', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isAgreedtoTC', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isAgreedtoTC')
    op.drop_column('artworks', 'forSale')
    # ### end Alembic commands ###
