"""added enum for community

Revision ID: 8bb589d27040
Revises: a9cb2295a234
Create Date: 2025-12-04 11:58:12.993589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8bb589d27040'
down_revision: Union[str, Sequence[str], None] = 'a9cb2295a234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'type')
    # ### end Alembic commands ###
