"""time stamp from serverside to clientside

Revision ID: 940cdee39e62
Revises: db0efc062cf2
Create Date: 2025-09-29 08:26:08.894011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '940cdee39e62'
down_revision: Union[str, Sequence[str], None] = 'db0efc062cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
