"""adding artworkimage table

Revision ID: 9f7ecde091d5
Revises: 3d8cdf4ee52b
Create Date: 2025-09-01 07:33:33.411802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f7ecde091d5'
down_revision: Union[str, Sequence[str], None] = '3d8cdf4ee52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
