"""artwork images

Revision ID: b1f9461d4ec0
Revises: 2061a16fa0b2
Create Date: 2025-07-01 22:19:12.552075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1f9461d4ec0'
down_revision: Union[str, Sequence[str], None] = '2061a16fa0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_column('artworks', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('artworks', 'images')
    # ### end Alembic commands ###
