"""price and quantity nullable true for our isSale logic

Revision ID: d53d0190b071
Revises: 6a85f5c7804d
Create Date: 2025-09-17 09:59:52.882427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd53d0190b071'
down_revision: Union[str, Sequence[str], None] = '6a85f5c7804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artworks', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('artworks', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artworks', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('artworks', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
