"""added profile_completion in user table

Revision ID: db0efc062cf2
Revises: 41eb479e28b1
Create Date: 2025-09-23 07:57:24.303624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db0efc062cf2'
down_revision: Union[str, Sequence[str], None] = '41eb479e28b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.add_column('users', sa.Column('profile_completion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completion')
    op.create_table('wishlist',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('artworkId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['artworkId'], ['artworks.id'], name=op.f('wishlist_ibfk_2')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('wishlist_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
