"""relationship and cascade

Revision ID: e4acb1b4a2b5
Revises: 289c912dea66
Create Date: 2025-12-08 09:31:07.657623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4acb1b4a2b5'
down_revision: Union[str, Sequence[str], None] = '289c912dea66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communities', 'type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('public', 'private', 'restricted', name='communitytype', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communities', 'type',
               existing_type=sa.Enum('public', 'private', 'restricted', name='communitytype', native_enum=False),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
